### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#153]
Workflow as follows:

Read in the file
`temp_path = ‘pathpathpath.qptiff’`

Create a Slide Object
`mif_slide = SlideData(temp_path, backend = “bioformats”, slide_type = types.Vectra)`

I am creating tiles like so

Create tiles from the slide
`tiles = mif_slide.generate_tiles(shape = 256)`
`list_of_tiles = list(tiles)`

However, I get the error:
```

---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/bioformats/formatreader.py in init_reader(self)

~/.local/lib/python3.8/site-packages/bioformats/formatreader.py in setId(self, path)

~/.local/lib/python3.8/site-packages/javabridge/jutil.py in call(o, method_name, sig, *args)

~/.local/lib/python3.8/site-packages/javabridge/jutil.py in fn(*args)

JavaException: /mnt/disks/ip_tiles/immunoprofile-raw/immunoprofile/Lung_Cancer/IP-18-J00055/ROI_ANALYSIS/IP_18_J00055_Scan1.qptiff (Too many open files)

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_7604/3079534046.py in <module>
      1 #Prototype the pipeline on a set of tiles
----> 2 list_of_tiles = list(tiles)
      3 # next(tiles)

~/pathml/pathml/core/slide_data.py in generate_tiles(self, shape, stride, pad, **kwargs)
    379             pathml.core.tile.Tile: Extracted Tile object
    380         """
--> 381         for tile in self.slide.generate_tiles(shape, stride, pad, **kwargs):
    382             # add masks for tile, if possible
    383             # i.e. if the SlideData has a Masks object, and the tile has coordinates

~/pathml/pathml/core/slide_backends.py in generate_tiles(self, shape, stride, pad, level)

~/pathml/pathml/core/slide_backends.py in extract_region(self, location, size, level)

~/.local/lib/python3.8/site-packages/bioformats/formatreader.py in __init__(self, path, url, perform_init)

~/.local/lib/python3.8/site-packages/bioformats/formatreader.py in init_reader(self)

AttributeError: 'JavaException' object has no attribute 'message'
```

**Comment by jacobrosenthaldfci** [comment]
I reproduced this with our testing data by creating a ton of small tiles:

````python
temp_path = "tests/testdata/small_vectra.qptiff"
mif_slide = SlideData(temp_path, backend = "bioformats", slide_type = types.Vectra)
tiles = mif_slide.generate_tiles(shape = 10)
list_of_tiles = list(tiles)
````
````
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2944, in _run_cell
    return runner(coro)
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3169, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3380, in run_ast_nodes
    self.showtraceback()
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2063, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1367, in structured_traceback
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1267, in structured_traceback
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1142, in structured_traceback
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1082, in format_exception_as_a_whole
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/ultratb.py", line 382, in find_recursion
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2061, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1101, in get_records
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/ultratb.py", line 248, in wrapped
  File "/opt/miniconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
  File "/opt/miniconda3/envs/pathml/lib/python3.8/inspect.py", line 1515, in getinnerframes
  File "/opt/miniconda3/envs/pathml/lib/python3.8/inspect.py", line 1473, in getframeinfo
  File "/opt/miniconda3/envs/pathml/lib/python3.8/inspect.py", line 708, in getsourcefile
  File "/opt/miniconda3/envs/pathml/lib/python3.8/inspect.py", line 737, in getmodule
  File "/opt/miniconda3/envs/pathml/lib/python3.8/inspect.py", line 721, in getabsfile
  File "/opt/miniconda3/envs/pathml/lib/python3.8/posixpath.py", line 379, in abspath
OSError: [Errno 24] Too many open files
````

**Comment by jacobrosenthaldfci** [comment]
I suspect that the problem is here: https://github.com/Dana-Farber-AIOS/pathml/blob/master/pathml/core/slide_backends.py#L316-L317

We start a new java VM and initialize a new `bioformats.ImageReader` each time we call `BioFormatsBackend.extract_region()`. But we don't kill the VM or close the ImageReader. 

According to their documentation [here](https://pythonhosted.org/python-bioformats/#bioformats.ImageReader) we should probably use ImageReader in a "with" scope so that they will automatically handle entering and exiting. And maybe we should also call `javabridge.kill_vm()` at the end of the method

**Comment by ryanccarelli** [comment]
I wrote a test and fixed this by putting ImageReader in a with scope.
When I ```javabridge.kill_vm()``` we get the error:
```
E           RuntimeError: Failed to start Java VM

../../anaconda3/envs/pathml/lib/python3.8/site-packages/javabridge/jutil.py:319: RuntimeError
```
Apparently this is the expected behavior https://stackoverflow.com/questions/51554355/python-javabridge-virtual-machine-only-works-once and we should not stop the VM.
