### ISSUE TITLE
Resolving dependencies between PathML and Deepcell

### ISSUE THREAD

**Issue by ryanccarelli** [Dana-Farber-AIOS/pathml#259]
**Describe the bug**
When we run pipelines for multiparametric images we often want to include models from deepcell https://github.com/vanvalenlab/deepcell-tf (especially for the SegmentMIF transform). It is difficult for users to solve the environment since installing deepcell downgrades packages like numpy to incompatible versions. This has caused installation problems for @MohamedOmar2020 and other internal users

**To Reproduce**
```python3
pipe = Pipeline(
    [
        CollapseRunsVectra(),
        SegmentMIF(
            model="mesmer",
            nuclear_channel=0,
            cytoplasm_channel=7,
            image_resolution=0.5,
        ),
        QuantifyMIF(segmentation_mask="cell_segmentation"),
    ]
)
dataset.run(pipe)
```
**Expected behavior**
We would expect this to run but following the default installation instructions (option 1 from pip) followed by ```pip install deepcell``` results in a series of numpy errors when we attempt to run the pipeline

**Working Solution**
These dependency problems are resolved (at least to the extent that the above pipeline can run) by upgrading numpy after deepcell installation as follows
```
conda create --name pathml python=3.8
conda activate pathml
sudo apt-get install openslide-tools g++ gcc libblas-dev liblapack-dev
conda install openjdk==8.0.152
pip install pathml
pip install deepcell
pip install --upgrade numpy
```
The question is: should we include this in our installation instructions for users who want to use multiparametric pipelines? Should we create a docker container for multiparametric pipelines? Should we  remove our dependency on deepcell and try to wrap the model more directly in PathML (or train our own)?

**Comment by jacobrosenthaldfci** [comment]
Ok I think I found what the problem is:

The most recent version of deepcell (v0.11.0) requires tensorflow~=2.5.1 which in turn requires numpy~=1.19.2. BUT the most recent version of python-bioformats (v4.0.5) requires python-javabridge==4.0.3, which in turn requires numpy>=1.20.1. This creates an incompatibility, that for some reason the pip dependency solver struggles to resolve.

To work around, we can specify an older version of python-bioformats, which will require an older version of python-javabridge, which will require an older version of numpy compatible with that tensorflow version.

So, a working environment with both pathml and deepcell can be created as follows (tested on my mac):
````
conda create --name pathml-deepcell python=3.8 openjdk==8.0.152 -y 
conda activate pathml-deepcell
pip install python-bioformats==4.0.0 deepcell pathml
````

I was able to set up the environment with the above with no errors:

````
(pathml-deepcell) Jacobs-MacBook-Pro:pathml jacobrosenthal$ conda list | grep 'numpy\|pathml\|deepcell\|tensorflow\|javabridge\|bioformats'
# packages in environment at /opt/miniconda3/envs/pathml-deepcell:
deepcell                  0.11.0                   pypi_0    pypi
deepcell-toolbox          0.10.3                   pypi_0    pypi
deepcell-tracking         0.5.4                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
pathml                    2.0.1                    pypi_0    pypi
python-bioformats         4.0.0                    pypi_0    pypi
python-javabridge         4.0.0                    pypi_0    pypi
tensorflow                2.5.2                    pypi_0    pypi
tensorflow-addons         0.13.0                   pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
````

I also confirmed that it worked by running `python -m pytest tests/integration_tests/test_pipeline_running.py`, and all the tests which rely on Mesmer passed. (I also had to add `conda install mkl`, but that might be specific to my laptop, idk if we'll need that on non-intel machines) 

@ryanccarelli @MohamedOmar2020  can you try this out on your end to see if this works?

Links:
- [python-bioformats setup.py history](https://github.com/CellProfiler/python-bioformats/commits/master/setup.py)
- [python-javabridge setup.py history](https://github.com/CellProfiler/python-javabridge/commits/master/setup.py)
- [deepcell tf requirement](https://github.com/vanvalenlab/deepcell-tf/blob/ec48625be3206bcc513783856bc42bd221bac9d0/setup.py#L65)
- [tf v2.5.1 numpy requirement](https://github.com/tensorflow/tensorflow/blob/8222c1cfc866126111f23bd9872998480cebf2c1/tensorflow/tools/pip_package/setup.py#L81)

**Comment by MohamedOmar2020** [comment]
Hi @jacobrosenthaldfci. I am trying it now on my mac. The installation is fine but I am getting this error when I import any function from pathml:
```
from pathml.core import SlideDataset
Traceback (most recent call last):
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/spams_wrap/spams_wrap.py", line 22, in swig_import_helper
    fp, pathname, description = imp.find_module(
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_spams_wrap'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-68b6d954fafc>", line 1, in <module>
    from pathml.core import SlideDataset
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/__init__.py", line 6, in <module>
    from .core import *
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/core/__init__.py", line 6, in <module>
    from .masks import Masks
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/core/masks.py", line 13, in <module>
    import pathml.core.h5managers
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/core/h5managers.py", line 17, in <module>
    from pathml.core.utils import readcounts
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/core/utils.py", line 15, in <module>
    import pathml.core.slide_data
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/core/slide_data.py", line 16, in <module>
    import pathml.preprocessing.pipeline
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/preprocessing/__init__.py", line 6, in <module>
    from .pipeline import Pipeline
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/preprocessing/pipeline.py", line 9, in <module>
    from pathml.preprocessing.transforms import Transform
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/pathml/preprocessing/transforms.py", line 15, in <module>
    import spams
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/spams/__init__.py", line 6, in <module>
    from .spams import *
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/spams/spams.py", line 9, in <module>
    import spams_wrap
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/spams_wrap/__init__.py", line 6, in <module>
    from .spams_wrap import *
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/spams_wrap/spams_wrap.py", line 34, in <module>
    _spams_wrap = swig_import_helper()
  File "/Users/mohamedomar/opt/anaconda3/envs/pathml-deepcell/lib/python3.8/site-packages/spams_wrap/spams_wrap.py", line 25, in swig_import_helper
    import _spams_wrap
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: numpy.core.multiarray failed to import
 
```

On your end, can you try to do the steps you mentioned but modifying the last command to `pip install python-bioformats==4.0.0 deepcell pathml --no-cache-dir`?

**Comment by jacobrosenthaldfci** [comment]
Thanks Mohamed, I was able to reproduce what you saw... It's because of something wrong in the spams package that we depend on. We really need to remove it..... (#142)

I was able to resolve by installing spams from conda forge, which apparently has a more stable version than on PyPI. Can you try the following steps and let me know if you run into more problems:

````
conda create --name pathml-deepcell python=3.8 openjdk==8.0.152 -y
conda activate pathml-deepcell
conda install numpy==1.19.5 python-spams -c conda-forge
pip install python-bioformats==4.0.0 deepcell pathml

# verify that installation worked and we can import from pathml
python -c "from pathml.core import SlideDataset"
````

Thanks 😊

**Comment by MohamedOmar2020** [comment]
Bingo! thanks Jacob, now it is working.  
On a separate note, I am running into the same issue which I got with Angeles #261 . I don't get this problem when I use my other conda environment in which I have pathml 1.0.1. 
Let's follow it up there.

**Comment by jacob-rosenthal** [comment]
For using deepcell, you should use the `environment.yml` file to set up the working environment, i.e. installation options 2 or 3. This hasn't been clear in the docs, so I added some clarification about this in the PR here: https://github.com/Dana-Farber-AIOS/pathml/pull/298

Thanks!!

**Comment by surya-narayanan** [comment]
Awesome. Thanks @jacob-rosenthal . 🚀
