### ISSUE TITLE
problem installing, owing to numpy not found

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#296]
Following the installation instructions on a new vm, I get the following error:

```
Collecting python-javabridge==4.0.3
  Downloading python-javabridge-4.0.3.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 77.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2debh72m/python-javabridge_3cb37e3899344394b74cdd83d5dfc4b8/setup.py", line 412, in <module>
          ext_modules=ext_modules(),
        File "/tmp/pip-install-2debh72m/python-javabridge_3cb37e3899344394b74cdd83d5dfc4b8/setup.py", line 100, in ext_modules
          from numpy import get_include
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

I think it gets resolved by installing numpy in the env first, I am not sure why this is happening, since you have numpy in the requirements.

**Comment by jacob-rosenthal** [comment]
I'm guessing this is with installation option 1 (pip install)? Is that correct?

Sounds like you found a fix? If so, could you open a PR?

Thanks!

**Comment by surya-narayanan** [comment]
Yes, this is with installation option 1. I don't think I found a fix that works fully. The fix (so far) is to do

`pip install numpy`

and then 

`pip install pathml`

I can create a new env and see if this works. If so, it could just be a matter of updating the `readme`, what do you think?.

**Comment by jacob-rosenthal** [comment]
Great, I will take a look on a fresh VM as well. Yes I agree, this seems like something we should update in the readme installation instructions if they aren't working!

**Comment by surya-narayanan** [comment]
Great, followed up with a PR #298
