### ISSUE TITLE
best way to extract anndata ( h5ad )  from hdf5 file

### ISSUE THREAD

**Issue by afshinmoradi** [Dana-Farber-AIOS/pathml#330]
Dear, 

I run cell segmentation and saved h5 files.
I loaded with bellow command
f= h5py.File('a.h5', "r") 
I want to extract annadata or csv from that. Could please let me know what is the best option

I used bellow comment it works
f['counts']['X'][()]

but  I got bellow error when I called obs dataset

>>> f['counts']['obs'][()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/scratch/medicine/afshin/app/miniconda3/envs/H5/lib/python3.10/site-packages/h5py/_hl/group.py", line 330, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'tuple'>

Thanks for your help

**Comment by jacob-rosenthal** [comment]
I suggest using `SlideData` instead of interacting with the raw h5 file for this. For example, try something like:

```
wsi = SlideData('a.h5')
counts = wsi.counts
```
