### ISSUE TITLE
Unable to read in all image layers in .vdi file, only index 0 is read in

### ISSUE THREAD

**Issue by RYY0722** [Dana-Farber-AIOS/pathml#364]
**HESlide and Slidedata only read in the top one image in .vdi file**
I use the `BioformatsReader` in `cellprofiler_core.readers.bioformats_reader` to read the ets file, which contains three images as shown in QuPath. However, only the image with index 0 is read in. 
 
**To Reproduce**
```python
from pathml.core import HESlide, SlideData, types
my_zeiss_zvi = HESlide("data/Image_06.vsi",
                         labels = {"target" : "HER-2"},
                         slide_type = types.HE)
``` 
It gives
```python
SlideData(name='Image_06.vsi',
        slide_type=SlideType(stain=HE, platform=None, tma=None, rgb=True, volumetric=None, time_series=None),
        filepath='data/Image_06.vsi',
        backend='bioformats',
        image shape: (61115, 130754),
        number of levels: 23,
        0 tiles: [],
        0 masks: [],
        1 labels: ['target'],
        counts=None)
````
The width and height is concordant with the full-resolution image. Does it indicate that the full resolution image is loaded?
However, it seems that only the label image is loaded. When I run `tile = my_zeiss_zvi.extract_region((0,0), (1000,1000), level=3).squeeze()`
It gave 
![image](https://github.com/Dana-Farber-AIOS/pathml/assets/60810000/49e0c45d-754a-405a-8c66-fd303af7e6c5)

It seems that only the top one image is loaded.
**Expected behavior**
Can I specify the associated .ets file to process the full-resolution image in python?

**Desktop (please complete the following information):**
 - OS: [VERSION="20.04.5 LTS (Focal Fossa)", ID=ubuntu, ID_LIKE=debian]

Thank you very much!!!!! I have been struggled for quite a long time to read .ets and .vsi files in python. Looking forward to the help and advice!!!

**Comment by RYY0722** [comment]
Thanks a lot for your reply!
- But I am wondering whether it can read the full-resolution image since the .vsi file is of only 2.72MB. Should I specify the associated .ets file? 
- How to read the desired image layer or the desired shape? Since when I called `my_zeiss_zvi.slide.generate_tiles()`, it only reads the label image instead of the HE image. 
- How to handle large image file? \
My .ets file is of 1.76GB and the .vsi file is of 2.72 MB. When I called `my_zeiss_zvi.slide.get_thumbnail()` or `extract_region((0,0), my_zeiss_zvi.slide.get_image_shape())`, the following error occurred.
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuyan/virtual_envs/torch38/lib/python3.8/site-packages/pathml/core/slide_backends.py", line 516, in get_thumbnail
    raise Exception(
Exception: Java arrays allocate maximum 32 bits (~2GB). Image size is (61115, 130754)
```
Would you give some suggestions regarding this situation? 

Thanks again!

**Comment by jacob-rosenthal** [comment]
- We rely on bioformats to know how to handle that image format, including how to handle the data being split into multiple files. I think it should work but I haven't ever tried with that particular file format before so I don't know
- You should be able to pass `level` argument to `generate_tiles()` to specify which level to use
- Instead of trying to load the entire image into memory, use the tile generator and process the image at tile-level. If you really want to have the full-resolution image in memory, then use the tile generator to extract the tiles into numpy arrays and then stitch the numpy arrays together into the full array.
